title: Workload Landing Zone
description: Workload Landing Zone developed by OCI RSA
schemaVersion: 1.1.0
version: "0.1"
locale: en
variableGroups:
  - title: Provider Variables
    visible: false
    variables:
      - api_fingerprint
      - api_private_key_path
      - region
      - tenancy_ocid
      - current_user_ocid
  - title: Tagging
    variables:
      - tag_cost_center
      - tag_geo_location
  - title: Compartment
    variables:
      - applications_compartment_id
      - workload_compartment_name
  - title: Global Resources Control
    variables:
      - deploy_global_resources
  - title: IAM
    variables:
      - network_compartment_name
      - network_compartment_id
      - show_extra_group_names
      - workload_storage_admins_group_name
      - workload_storage_users_group_name
      - workload_admins_group_name
      - workload_users_group_name
      - database_admins_group_name
  - title: VCN
    variables:
      - vcn_id
      - nat_gateway_id
      - private_subnet_cidr_block
      - private_subnet_dns_label
      - database_subnet_cidr_block
      - database_subnet_dns_label
  - title: Sandbox Mode
    variables:
      - is_sandbox_mode_enabled

variables:
  #Provider Variables
  api_fingerprint:
    type: string
    description: The fingerprint of API
    default: "Value not required in Oracle Resource Manager."
    title: Api Fingerprint
  api_private_key_path:
    type: string
    description: The local path to the API private key
    default: "Value not required in Oracle Resource Manager."
    title: Api Private Key Path
  region:
    type: string
    description: the OCI region
    title: Region
  tenancy_ocid:
    type: string
    description: The OCID of tenancy
    title: Tenancy OCID
  current_user_ocid:
    type: string
    description: OCID of the current user
    title: Current User OCID

  # Tagging
  tag_cost_center:
    type: string
    description: CostCenter tag value. Allows printable ASCII, excluding periods (.) and spaces and max 100 characters.
    required: true
    title: Tag Cost Center
    pattern: ^((?!\.| )[ -~]){1,100}$
  tag_geo_location:
    type: string
    description: GeoLocation tag value. Allows printable ASCII, excluding periods (.) and spaces and max 100 characters.
    required: true
    title: Tag Geo Location
    pattern: ^((?!\.| )[ -~]){1,100}$

  # Compartments
  workload_compartment_name:
    type: string
    description: Name of the workload compartment. Maximum 100 characters, including letters, numbers, periods, hyphens, underscores, and is unique within its parent compartment.
    required: true
    title: Workload Compartment Name
    pattern: ^([\w\.-]){1,100}$
  applications_compartment_id:
    type: string
    description: OCID of the top level application compartment. 
    required: true
    title: Applications Compartment OCID

  # Global Resources Control
  deploy_global_resources:
    type: boolean
    description: Whether to deploy global resources, including tenancy level IAM service and Security service (Cloud Guard, VSS, Flow Log). Choose false if extend your Landing Zone to another region.
    required: true
    defaul: true
    title: Deploy Global Resources

  # IAM
  network_compartment_name:
    type: string
    description: Name of the network compartment. Maximum 100 characters, including letters, numbers, periods, hyphens, underscores, and is unique within its parent compartment.
    required: true
    title: Network Compartment Name
    pattern: ^([\w\.-]){1,100}$
  network_compartment_id:
    type: string
    description: OCID of the network compartment. 
    required: true
    title: Network Compartment OCID
  show_extra_group_names:
    type: boolean
    default: false
    required: false
    title: Override default group names
  workload_admins_group_name:
    type: string
    description: The name for the workload administrators group. Maximum 100 characters, including letters, numbers, periods, hyphens, underscores, and is unique across all groups.
    required: true
    title: Workload Admins Group Name
    visible: show_extra_group_names
    pattern: ^([\w\.-]){1,100}$
  workload_storage_admins_group_name:
    type: string
    description: The name for the workload storage administrators group. Maximum 100 characters, including letters, numbers, periods, hyphens, underscores, and is unique across all groups.
    required: true
    title: Workload Storage Admins Group Name
    visible: show_extra_group_names
    pattern: ^([\w\.-]){1,100}$
  workload_storage_users_group_name:
    type: string
    description: The name for the workload storage users group. Maximum 100 characters, including letters, numbers, periods, hyphens, underscores, and is unique across all groups.
    required: true
    title: Workload Storage Users Group Name
    visible: show_extra_group_names
    pattern: ^([\w\.-]){1,100}$
  workload_users_group_name:
    type: string
    description: The name for the workload users group. Maximum 100 characters, including letters, numbers, periods, hyphens, underscores, and is unique across all groups.
    required: true
    title: Workload Users Group Name
    visible: show_extra_group_names
    pattern: ^([\w\.-]){1,100}$
  database_admins_group_name:
    type: string
    description: The name for the database admins group. Maximum 100 characters, including letters, numbers, periods, hyphens, underscores, and is unique across all groups.
    required: true
    title: Database Admins Group Name
    visible: show_extra_group_names
    pattern: ^([\w\.-]){1,100}$
  # VCN
  vcn_id:
    type: string
    description: OCID of the VCN to attach the workload subnets. 
    required: true
    title: VCN OCID
  nat_gateway_id:
    type: string
    description: OCID of the NAT Gateway. 
    required: true
    title: NAT Gateway OCID
  private_subnet_cidr_block:
    type: string
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1][0-9]|[2][0-9]))$
    description: Private Subnet CIDR Block (one per workload, maximum of five)
    required: true
    title: Private Subnet CIDR Blocks
  private_subnet_dns_label:
    type: string
    pattern: ^[a-zA-Z][a-zA-Z0-9]{1,14}$
    description: Private Subnet DNS Label (one per workload, maximum of five). Allowed maximum 15 alphanumeric characters and must start with a letter.
    required: true
    title: Private Subnet DNS Labels
  database_subnet_cidr_block:
    type: string
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1][0-9]|[2][0-9]))$
    description: Database Subnet CIDR Block (one per workload, maximum of five)
    required: true
    title: Database Subnet CIDR Blocks
  database_subnet_dns_label:
    type: string
    pattern: ^[a-zA-Z][a-zA-Z0-9]{1,14}$
    description: Database Subnet DNS Label (one per workload, maximum of five). Allowed maximum 15 alphanumeric characters and must start with a letter.
    required: true
    title: Database Subnet DNS Labels

  # Sandbox Mode
  is_sandbox_mode_enabled:
    type: boolean
    title: Enable Sandbox Mode?
    description: Enable the sandbox mode if using the stack for development or demonstrations. Adds a unique suffix for all the tenancy level resources.

outputs:
  more_info_url:
    type: link
    displayText: For more information, please see the Cloud Adoption Framework - Technical Implementation
primaryOutputButton: more_info_url
